# Generated by Django 4.1.3 on 2022-11-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('userId', models.UUIDField(unique=True)),
                ('username', models.CharField(max_length=310)),
                ('profile_picture', models.URLField()),
                ('contact_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('friends', models.JSONField(null=True)),
                ('friend_requests', models.JSONField(null=True)),
            ],
        ),
    ]
