# Generated by Django 4.1.3 on 2022-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_alter_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
