# Generated by Django 4.1.3 on 2022-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=250, verbose_name='userId')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField()),
            ],
        ),
    ]
